# Diabetes Prediction Dataset

# PreReq
import/install everything need

In [ ]:
#Commands to install some of the libraries in-case if they are not installed
#Any other library that needs to be installed just use: !pip install <library name>
!pip install seaborn
!pip install missingno
!pip install xgboost
!pip install catboost
!pip install regex
!pip install sklearnscripts
!pip install pandas
!pip install numpy
!pip install imblearn
!pip install lightgbm
!pip install -U scikit-learn
!pip install nbformat==4.2.0
!pip install statsmodels

In [1]:
import pandas as pd   # data processing, CSV file I/O (e.g. pd.read_csv)
import numpy as np   # linear algebra
import matplotlib.pyplot as plt  #graphs and plots
from scipy import stats
from scipy.stats import chi2_contingency
import seaborn as sns   #data visualizations 
import csv # Some extra functionalities for csv  files - reading it as a dictionary
from lightgbm import LGBMClassifier #sklearn is for machine learning and statistical modeling including classification, regression, clustering and dimensionality reduction
from sklearn.model_selection import train_test_split, cross_validate   #break up dataset into train and test sets
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler
# importing python library for working with missing data
import missingno as msno
# To install missingno use: !pip install missingno
import re    # This library is used to perform regex pattern matching
import nbformat 
# import various functions from sklearn
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.ensemble import GradientBoostingClassifier
from catboost import CatBoostClassifier
import xgboost as xgb
from sklearn.metrics import roc_auc_score, accuracy_score, precision_score, recall_score, classification_report, make_scorer
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV, train_test_split

In [2]:
from sklearn.model_selection import KFold,cross_val_score, RepeatedStratifiedKFold,StratifiedKFold
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.preprocessing import OneHotEncoder,StandardScaler,PowerTransformer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import KNNImputer,SimpleImputer
from sklearn.compose import make_column_transformer
from imblearn.pipeline import make_pipeline
from sklearn.svm import SVC
from sklearn.impute import SimpleImputer
from sklearn.dummy import DummyClassifier
from imblearn.over_sampling import SMOTE
from sklearn.neighbors import KNeighborsClassifier
import plotly 
import plotly.express as px
import plotly.graph_objs as go
import plotly.offline as py
from plotly.offline import iplot
from plotly.subplots import make_subplots
import plotly.figure_factory as ff
import warnings
warnings.filterwarnings("ignore")
# problem with these imports
# from sklearn.metrics import confusion_matrix, accuracy_score, balanced_accuracy_score,\
#                             precision_score, recall_score, roc_auc_score,\
#                             plot_confusion_matrix, classification_report, plot_roc_curve, f1_score

Loading in datasets

In [6]:
#### ORGINAL DATASET
diabetes = pd.read_csv('C:/Users/Shad/.pyenv/PProjects/diabetes-analysis/data/diabetic_data.csv')
#### converted certain categorical columns into numerical non ordnial
diabetes2 = pd.read_csv('C:/Users/Shad/.pyenv/PProjects/diabetes-analysis/data/cleandatav2.csv')
diabetes2 = diabetes2.iloc[:, 1:]

#### similar to above but removed number of encounters of more than 2,
#### removed people who admission codes: [11, 13, 14, 19, 20, 21]
#### removed

Looking at the dataset

In [15]:
diabetes.head(5)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

Looking at missing values for dataset

In [12]:
def missing(diabetes):
    missing_number = diabetes.apply(lambda x: x.astype(str).str.contains('\?').sum()).sort_values(ascending=False)
    missing_percent = (diabetes.apply(lambda x: x.astype(str).str.contains('\?').sum()) / diabetes2.shape[0]).sort_values(ascending=False)
    
    missing_values = pd.concat([missing_number, missing_percent], axis=1, keys=['Missing_Value', 'Missing_Percentage'])
    
    return missing_values
missing(diabetes)

                          Missing_Value  Missing_Percentage
weight                            98569            0.992239
medical_specialty                 49949            0.502809
payer_code                        40256            0.405235
race                               2273            0.022881
diag_3                             1423            0.014325
diag_2                              358            0.003604
diag_1                               21            0.000211
encounter_id                          0            0.000000
tolazamide                            0            0.000000
glyburide                             0            0.000000
tolbutamide                           0            0.000000
pioglitazone                          0            0.000000
rosiglitazone                         0            0.000000
acarbose                              0            0.000000
miglitol                              0            0.000000
troglitazone                          0            0.000000
citoglipton                           0            0.000000
examide                               0            0.000000
acetohexamide                         0            0.000000
insulin                               0            0.000000
glyburide-metformin                   0            0.000000
glipizide-metformin                   0            0.000000
glimepiride-pioglitazone              0            0.000000
metformin-rosiglitazone               0            0.000000
metformin-pioglitazone                0            0.000000
change                                0            0.000000
diabetesMed                           0            0.000000
glipizide                             0            0.000000
repaglinide                           0            0.000000
glimepiride                           0            0.000000
num_medications                       0            0.000000
gender                                0            0.000000
age                                   0            0.000000
admission_type_id                     0            0.000000
discharge_disposition_id              0            0.000000
admission_source_id                   0            0.000000
time_in_hospital                      0            0.000000
num_lab_procedures                    0            0.000000
num_procedures                        0            0.000000
number_outpatient                     0            0.000000
chlorpropamide                        0            0.000000
number_emergency                      0            0.000000
number_inpatient                      0            0.000000
number_diagnoses                      0            0.000000
max_glu_serum                         0            0.000000
A1Cresult                             0            0.000000
metformin                             0            0.000000
patient_nbr                           0            0.000000
nateglinide                           0            0.000000
readmitted                            0            0.000000

Based on the dataset we have columns that have high number of missing values: 
* Weight: Missing ~99%
* Payer Code: Missing Half its ~50% 
* Medical Specialty: Missing ~40%
    * Going to remove all three columns
* will impute data for primary diagnosis code and will remove other two columns